#OBJS specifies which files to compile as part of the project
OBJS = main.cpp

#OBJ_NAME specifies the name of our exectuable
OBJ_NAME = Krotharkia

#This is the target that compiles our executable
all : $(OBJS)
	g++ src/$(OBJS) -w -lSDL2 -o $(OBJ_NAME) -I/include